package fechascomotresnumeros;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*Escribir un aplicación que acepte fechas como tres números
(dd, mm, aaaa) y las visualice del modo usual.*/
/**
 * @author JonathanDiaz
 */
public class interfaz extends javax.swing.JFrame {

    public void Cerrar() {//crear un metodo para cerrar.
        String botones[] = {"SI", "NO"};//botones de opcion.
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicacion?",
                "Cerrar", 0, 0, null, botones, this);
        if (eleccion == JOptionPane.YES_OPTION) {
            this.dispose();
        } else if (eleccion == JOptionPane.NO_OPTION) {
        }
    }

    public int contadorDia() {//metodo para limitar el ingreso de numeros.
        String Dia = TxtDia.getText().replaceAll("[' '\n]", "");
        int num = 2 - Dia.length();//solo se podra ingresar 2 caracteres
        return num;
    }

    public int contadorMes() {//metodo para limitar el ingreso de numeros.
        String Mes = TxtMes.getText().replaceAll("[' '\n]", "");
        int num2 = 2 - Mes.length();//solo se podra ingresar 2 caracteres
        return num2;
    }

    public int contadorAnio() {//metodo para limitar el ingreso de numeros.
        String Anio = TxtAnno.getText().replaceAll("[' '\n]", "");
        int num2 = 4 - Anio.length();//solo se podra ingresar 2 caracteres
        return num2;

    }

    public interfaz() {
        initComponents();

        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);//no haga nada el boton de cerrar.
        this.addWindowListener(new WindowAdapter() {//utilizar el evento creado
            @Override
            public void windowClosing(WindowEvent e) {//evento para cerrar.
                Cerrar();//llamar a la funcion de Cerrar.
            }
        });

        //ponemos un icono al formulario.
        Toolkit t = Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/btns/java.png")));

        // llamamos a la Funcion de Solo Numeros.
        Principal.SNumeros(TxtDia);
        Principal.SNumeros(TxtMes);
        Principal.SNumeros(TxtAnno);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LblDia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtDia = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtMes = new javax.swing.JTextPane();
        LblMes = new javax.swing.JLabel();
        LblAnno = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TxtAnno = new javax.swing.JTextPane();
        LblFecha = new javax.swing.JLabel();
        CmdAceptar = new javax.swing.JButton();
        CmdLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblDia.setText("Dia :");

        TxtDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDiaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TxtDia);

        TxtMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMesKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(TxtMes);

        LblMes.setText("Mes :");

        LblAnno.setText("Año:");

        TxtAnno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAnnoKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(TxtAnno);

        CmdAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btns/aceptar.png"))); // NOI18N
        CmdAceptar.setToolTipText("Aceptar");
        CmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdAceptarActionPerformed(evt);
            }
        });

        CmdLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btns/nuevo.png"))); // NOI18N
        CmdLimpiar.setToolTipText("Nuevo");
        CmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblMes)
                            .addComponent(LblAnno, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmdAceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CmdLimpiar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblMes)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LblDia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblAnno)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CmdAceptar)
                        .addGap(7, 7, 7)
                        .addComponent(CmdLimpiar)))
                .addGap(10, 10, 10)
                .addComponent(LblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdAceptarActionPerformed
        // evitar que se ingrese campos vacios.
        // si txt esta vacios o txt esta vacios.
        if (TxtDia.getText().isEmpty() || TxtMes.getText().isEmpty() || TxtAnno.getText().isEmpty()) {
            // enviar un mensaje de error.

//JOptionPane: Es una librería que nos permite mostrar mensajes de forma gráfica en una aplicación. 
//showMessageDialog: Este tipo de mensajes son utilizados para informar al usuario algo.
            JOptionPane.showMessageDialog(null, "Ingrese los numeros: ", "Error", JOptionPane.WARNING_MESSAGE);

// caso contrario.
        } else {

            String CadMes = null;
            int Mes, dia, anio;
            dia = Integer.parseInt(TxtDia.getText());
            Mes = Integer.parseInt(TxtMes.getText());
            anio = Integer.parseInt(TxtAnno.getText());

            /*La instrucción switch es una forma de expresión de un anidamiento múltiple de 
instrucciones if, else. Su uso no puede considerarse, por tanto, estrictamente 
necesario, puesto que siempre podrá ser sustituida por el uso de if. No obstante, 
a veces nos resultará útil al introducir mayor claridad en el código.     */
            switch (Mes) {

                case 1:
                    CadMes = "Enero";
                    break;
                case 2:
                    CadMes = "Febrero";
                    break;
                case 3:
                    CadMes = "Marzo";
                    break;
                case 4:
                    CadMes = "Abril";
                    break;
                case 5:
                    CadMes = "Mayo";
                    break;
                case 6:
                    CadMes = "Junio";
                    break;
                case 7:
                    CadMes = "Julio";
                    break;
                case 8:
                    CadMes = "Agosto";
                    break;
                case 9:
                    CadMes = "Setiembre";
                    break;
                case 10:
                    CadMes = "Octubre";
                    break;
                case 11:
                    CadMes = "Noviembre";
                    break;
                case 12:
                    CadMes = "Diciembre";
                    break;
                /*
La cláusula default es opcional y representa las instrucciones que se ejecutarán en caso de que no se 
verifique ninguno de los casos evaluados. El último break dentro de un switch 
(en default si existe esta cláusula, o en el último caso evaluado si no existe default)
también es opcional, pero lo incluiremos siempre para ser metódicos.                  
                 */
                default:
                 
                    JOptionPane.showMessageDialog(null, "Error de datos...", "Error", JOptionPane.WARNING_MESSAGE);

            }
            LblFecha.setText(String.valueOf(dia + " de " + CadMes + " del " + anio));

        }
    }//GEN-LAST:event_CmdAceptarActionPerformed

    private void CmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdLimpiarActionPerformed

// Se limpian los cuadros de textos a través del método setText() 
        TxtDia.setText("");
        TxtMes.setText("");
        TxtAnno.setText("");
        LblFecha.setText("");
//y con el método requestFocus() se pasa el cursor al objeto de control Txt.
        TxtDia.requestFocus();
    }//GEN-LAST:event_CmdLimpiarActionPerformed

    private void TxtDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDiaKeyTyped
        if (contadorDia() == 0) {//cuando el contador llege a 0
            evt.consume();// no permita el ingreso de mas caracteres
        }
    }//GEN-LAST:event_TxtDiaKeyTyped

    private void TxtMesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMesKeyTyped
        if (contadorMes() == 0) {//cuando el contador llege a 0
            evt.consume();// no permita el ingreso de mas caracteres
        }
    }//GEN-LAST:event_TxtMesKeyTyped

    private void TxtAnnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAnnoKeyTyped
        if (contadorAnio() == 0) {//cuando el contador llege a 0
            evt.consume();// no permita el ingreso de mas caracteres
        }
    }//GEN-LAST:event_TxtAnnoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdAceptar;
    private javax.swing.JButton CmdLimpiar;
    private javax.swing.JLabel LblAnno;
    private javax.swing.JLabel LblDia;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblMes;
    private javax.swing.JTextPane TxtAnno;
    private javax.swing.JTextPane TxtDia;
    private javax.swing.JTextPane TxtMes;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
